# Site settings
title: Sam Machek
email: sammachek5@gmail.com
description: > # keep this and put description below
  Audio Engineer and Sound Designer
url: "SamMachekPortfolio.github.io" # the base hostname & protocol for your site
linkedin_url: "www.linkedin.com/in/sam-machek-410247382"
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
collections:
  otherposts:
    output: true